### PR TITLE
Ion/circle-physics

### PR DESCRIPTION
**Pull request by ionisea**
the old one seems to have broken

### CODE REVIEW

**Review by gigamonkey — COMMENTED** [review]
So this PR is very hard to review because you copied a bunch of files from one directory to another, presumably because you wanted a clean playground to play in. But that will actually make it much harder to merge things later on because the changes you make here will not be related to changes that other people make in the `physics` directory. I would advise that you not merge this.

To help out, I made a branch `ion/cicle-physics` that contains your code but transplanted into the physics branch. (I also ran `prettier` on main first and committed that, then transplanted your code and ran `prettier` on it before committing to minimize the spurious diffs. Everyone else should run prettier on their own branches to minimize the diffs with `main`. That's not caused by this situation; just a good idea in general.)

@ionisea you can make a PR from the branch I made and continue working there and then I can review your code without looking at twenty other files that you didn't really change.

**Comment by ionisea** [comment]
ok

**Comment by ionisea** [comment]
@gigamonkey;
The idea of this circle sim is to be basically a different project, which is why it is in a new project; meaning I do not intend to bring these changes back into main. Most things about the code are completely different from this circle base I am working from and the main project. I don't think it makes much sense to override the main project with this code as this code is incompatible with normal shapes (mostly).
I may be misunderstanding what you mean to do with this new branch, but from what I can see it is just erasing the old code and replacing it with my circle one.
I see that it is basically impossible to tell which changes have been made, but I think by merging this future commits on my branch will be visible

Please clarify what is meant to be done with the new branch

**Comment by lashlockbhs** [comment]
no its not

**Comment by lashlockbhs** [comment]
We should try to make create a physics engine which works with circles and shapes, cause up to this point all our code has been to make shapes, and I don't want to just waste it all.

**Review by lashlockbhs — COMMENTED** [review]
You rewrote everything but just for cirlces, |:

**Comment by gigamonkey** [comment]
Another way to deal with this PR is for you to manually transplant the bits of code from your directory back into the main directory to create a best of both worlds version which can be reviewed relative to the other stuff that's going on in the main branch and merged. You can even merge this PR first and then start putting code into the other directory in separate PRs but you should do that now to get all the code into one place ASAP.

**Comment by lashlockbhs** [comment]
OK

**Review by lashlockbhs — COMMENTED** [review]
llmg!

**Review by lashlockbhs — APPROVED** [review]
lgtm!111

**Review by szetingchen — APPROVED** [review]
worst circle drawer ever

**Comment by ionisea** [comment]
For Mr. Seibel and Collaborators-

THIS IS NOT YET DONE. There are various improvements and bug fixes that need to be introduced, but I wanted to get this merged into main so that it could be possible for us to collaborate on it, and so that it was obvious which changes I'm making.

**Pull request merged**
